### ISSUE TITLE
ldap_error: Net::LDAP::Error, no start_tls result

### ISSUE THREAD

**Issue by lukebrannon** [jonmbake/discourse-ldap-auth#19]
I've installed and configured the discourse-ldap-auth plugin and configured it at thus:
```
  ldap_enabled:
    default: true
  ldap_user_create_mode:
    default: 'auto'
  ldap_hostname:
    default: 'my.ldaps.com'
  ldap_port:
    default: 636
  ldap_method:
    default: 'tls'
  ldap_base:
    default: 'ou=people,dc=myServer,dc=net'
  ldap_uid:
    default: 'uid'
  ldap_bind_dn:
    default: 'uid=binduser,ou=people,dc=myServer,dc=net'
  ldap_password:
    default: '#########'
  ldap_filter:
    default: ''
```
In the app production.log I'm getting ldap_error: Net::LDAP::Error, no start_tls result
On my ldap server, I'm getting: slapd: closed (TLS negotiation failure)

Is it possible to increase the logging produced by discourse-ldap-auth?
